/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:386bc20a-ed18-416f-9231-334134e712fc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9CM90R8rR",
    "aws_user_pools_web_client_id": "2qe4l2elp04h9ihsb6ve505vcl",
    "oauth": {}
};


export default awsmobile;
